### ISSUE TITLE
出现的问题

### ISSUE THREAD

**Issue by mcck** [zuley/vue-color-picker#1]
我用 npm install vue-color-picker --save 安装的，却出现这样问题
![qq 20180829165730](https://user-images.githubusercontent.com/20223048/44777269-c43f2f80-abac-11e8-94c1-f947fb0a8649.png)
![qq 20180829165803](https://user-images.githubusercontent.com/20223048/44777270-c4d7c600-abac-11e8-9c06-b1c1dd0c6b02.png)

**Comment by zuley** [comment]
这个没有发布到 npm，不能使用 npm 安装哦。你这边可以拷贝组件代码过去用。

**Comment by zuley** [comment]
这个没有发布到 npm，不能使用 npm 安装哦。你这边可以拷贝组件代码过去用。 @mcck

**Comment by mcck** [comment]
好的，谢谢
