### ISSUE TITLE
该库会覆盖我ui组件里面的button的解析

### ISSUE THREAD

**Issue by fangbing0565** [zuley/vue-color-picker#11]
使用案例：
先引入iview的Button组件
再引入 vcolorpicker组件，一起使用，就会出现Button内容变成了你好
原本的button被解析成了 
`<div>你好</div>`

目前暂时只能通过先引入vcolorpicker,再引入ui组件的Button组件来避免该问题

**Comment by zuley** [comment]
你可以仔细检查下自己的项目，看看是不是哪里没注意。我这个颜色选择器组件里面没有“你好”这些内容的。
