### ISSUE TITLE
项目打包的时候会报错 npm run build的时候

### ISSUE THREAD

**Issue by zhouxuexin** [zuley/vue-color-picker#2]
![image](https://user-images.githubusercontent.com/21442790/48824606-b958fd00-ed9f-11e8-8f90-8b28ba1edc4e.png)

**Comment by 18883278826** [comment]
vue.config.js 里面chainWebpack配置报错。。。npm run lib时报错，请问大神这是什么原因呢，好像说的是这种写法不对，是版本的问题么？？
![e8a_s8j4 uvd y4l0 t pr](https://user-images.githubusercontent.com/22711539/50629061-ffe07080-0f75-11e9-8260-650a97ba8a5f.png)

**Comment by fengxianqi** [comment]
> vue.config.js 里面chainWebpack配置报错。。。npm run lib时报错，请问大神这是什么原因呢，好像说的是这种写法不对，是版本的问题么？？
> ![e8a_s8j4 uvd y4l0 t pr](https://user-images.githubusercontent.com/22711539/50629061-ffe07080-0f75-11e9-8260-650a97ba8a5f.png)

我也遇到这个问题了，然后发现是include的问题，需要这样配置：
`  chainWebpack: config => {
    config.module
      .rule('js')
      .include.add(path.resolve(__dirname, 'packages')).end()
      .use('babel')
      .loader('babel-loader')
      .tap(options => {
        // 修改它的选项...
        return options
      })
  }`

**Comment by 18883278826** [comment]
> > vue.config.js 里面chainWebpack配置报错。。。npm run lib时报错，请问大神这是什么原因呢，好像说的是这种写法不对，是版本的问题么？？
> > ![e8a_s8j4 uvd y4l0 t pr](https://user-images.githubusercontent.com/22711539/50629061-ffe07080-0f75-11e9-8260-650a97ba8a5f.png)
> 
> 我也遇到这个问题，需要这样配置：
> 
> ```js
>   chainWebpack: config => {
>     config.module
>       .rule('js')
>       .include.add(path.resolve(__dirname, 'packages')).end()
>       .use('babel')
>       .loader('babel-loader')
>       .tap(options => {
>         // 修改它的选项...
>         return options
>       })
>   }
> ```

path哪儿来的？？

**Comment by 18883278826** [comment]
> > vue.config.js 里面chainWebpack配置报错。。。npm run lib时报错，请问大神这是什么原因呢，好像说的是这种写法不对，是版本的问题么？？
> > ![e8a_s8j4 uvd y4l0 t pr](https://user-images.githubusercontent.com/22711539/50629061-ffe07080-0f75-11e9-8260-650a97ba8a5f.png)
> 
> 我也遇到这个问题，需要这样配置：
> 
> ```js
>   chainWebpack: config => {
>     config.module
>       .rule('js')
>       .include.add(path.resolve(__dirname, 'packages')).end()
>       .use('babel')
>       .loader('babel-loader')
>       .tap(options => {
>         // 修改它的选项...
>         return options
>       })
>   }
> ```

path哪儿来的也，能看看你的config文件么？

**Comment by neighbourwang** [comment]
![image](https://user-images.githubusercontent.com/19516616/52549530-94a87a80-2e0e-11e9-8f23-e8240582350f.png)

**Comment by yangguojin** [comment]
npm install vcolorpicker -S执行报错：
npm WARN checkPermissions Missing write access to E:\project\lzb4ui\node_modules\extglob\node_modules\is-extglob
npm WARN checkPermissions Missing write access to E:\project\lzb4ui\node_modules\isobject\node_modules\isarray
npm WARN checkPermissions Missing write access to E:\project\lzb4ui\node_modules\micromatch\node_modules\is-glob
npm WARN checkPermissions Missing write access to E:\project\lzb4ui\node_modules\micromatch\node_modules\is-extglob
npm WARN checkPermissions Missing write access to E:\project\lzb4ui\node_modules\yargs\node_modules\camelcase
npm WARN checkPermissions Missing write access to E:\project\lzb4ui\node_modules\isobject\node_modules
npm ERR! path E:\project\lzb4ui\node_modules\extglob\node_modules\is-extglob
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall access
npm ERR! enoent ENOENT: no such file or directory, access 'E:\project\lzb4ui\node_modules\extglob\node_modules\is-extglob'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Joseph\AppData\Roaming\npm-cache\_logs\2019-04-03T03_22_33_082Z-debug.log
————
使用cnpm安装没问题，但是我需要写入package-lock.json。
安装其他依赖不会有问题，请给出解决方案，谢谢。

**Comment by xueqiliu** [comment]
"lib": "vue-cli-service build --target lib --name cube-plugin --dest lib  src/index.js "
  我也想发布一个包， 照着你的写的， 为啥一直报错
 npm install --save ~entry
 求帮忙

**Comment by zuley** [comment]
> ```
> "lib": "vue-cli-service build --target lib --name cube-plugin --dest lib  src/index.js "
> ```
> 我也想发布一个包， 照着你的写的， 为啥一直报错
> npm install --save ~entry
> 求帮忙

请提供报错截图信息等，详细一点

**Comment by zuley** [comment]
> node_modules

看报错的提示是写权限错误哦
