### ISSUE TITLE
 按照知乎上的文章   从零开始：Vue cli3 库模式搭建组件库并发布到npm  运行报错

### ISSUE THREAD

**Issue by jscgq** [zuley/vue-color-picker#3]
根据教程到文章 `四、配置项目以支持新的目录结构`就开始报错
![image](https://user-images.githubusercontent.com/26852583/48976416-3519b900-f0c2-11e8-8a06-bf83f353a330.png)

把vue.config.js 和package.json都复制过来了依旧报错，根据cli3官网例子和webpack-chain例子是应该能运行的，但是都是跑不了

从这个项目clone过来不改变package-lock.json才能运行，不太清楚cli3为何同样的版本package-lock.json是不一样的，请教下作者

**Comment by zuley** [comment]
具体出现的原因不清楚，估计是依赖版本不一样有更新。你可以尝试修改下 add('packages') ，修改成add('/packages')
